run:
  deadline: 10m
  concurrency: 1
  tests: true
  modules-download-mode: vendor
linters:
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - typecheck
    - varcheck
    - dupl
    - goconst
    - gofmt
    - golint
    - unconvert
    - gosimple
    - unused
    - staticcheck
    - structcheck

issues:
  max-per-linter: 0
  max-same-issues: 0
