run:
  deadline: 10m
  concurrency: 1
  tests: true
  modules-download-mode: vendor
linters:
  enable-all: false
  enable:
    - errcheck
    - govet
    - ineffassign
    - typecheck
    - dupl
    - goconst
    - gofmt
    - unconvert
    - gosimple
    - unused
    - staticcheck
    - unused
    - revive

issues:
  max-per-linter: 0
  max-same-issues: 0
